import ListPage from './ListTemplate';
import EditPage from './EditTemplate';
import AddPage from './AddTemplate';
import ModifyPage from './ModifyTemplate';
import DetailPage from './DetailTemplate';
import RichDetailPage from './RichDetailTemplate';
import DetailRichPage from './DetailRichTemplate';
import EditTable from './EditTableTemplate';
import CardsPage from './CardsTemplate';
import ErrorBounDary from './ErrorBounDary';
export { ListPage, EditPage, AddPage, DetailPage, RichDetailPage, ModifyPage, DetailRichPage, EditTable, CardsPage, ErrorBounDary };
